name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código
      - name: Checkout código
        uses: actions/checkout@v4

      # 2. Instalar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Instalar dependencias
      - name: Instalar dependencias
        run: npm install

      # 4. Ejecutar pruebas unitarias
      - name: Ejecutar pruebas
        run: npm test

      # 5. Login a Docker Hub
      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Build y push de la imagen Docker
      - name: Build y push imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mi-app-devops:latest

      # 7. Deploy a Render (webhook)
      - name: Deploy a Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"